# Generated by Django 4.2 on 2023-06-14 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateField(auto_created=True)),
                ('created', models.DateField(auto_created=True)),
                ('active', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('react_by', models.JSONField(default=dict)),
                ('flagged_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateField(auto_created=True)),
                ('created', models.DateField(auto_created=True)),
                ('point', models.IntegerField(default=10)),
                ('recipients', models.JSONField(default=list)),
                ('sender', models.CharField(max_length=254)),
                ('hashtags', models.JSONField(default=list, null=True)),
                ('image', models.ImageField(max_length=255, null=True, upload_to='photos/user_form')),
                ('gif', models.CharField(max_length=500, null=True)),
                ('link', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('flag_transaction', models.BooleanField(default=False)),
                ('react_by', models.JSONField(default=dict)),
                ('comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.comments')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
