# Generated by Django 4.2 on 2023-06-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='react_by',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
