# Generated by Django 4.2 on 2023-06-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_comments_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='sisid',
            field=models.UUIDField(auto_created=True, default=111111),
        ),
    ]
