# Generated by Django 4.2 on 2023-06-14 18:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_posts_sisid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='id',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='sisid',
        ),
        migrations.AddField(
            model_name='posts',
            name='sys_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
